SELECT
    AUTHOR_ID,
    AUTHOR_NAME,
    T2.CATEGORY,
    SUM(T1.SALES * T2.PRICE) AS SALES
FROM BOOK_SALES T1
JOIN
    (SELECT
        BOOK_ID,
        A.AUTHOR_ID,
        AUTHOR_NAME,
        CATEGORY,
        PRICE
    FROM BOOK B
    JOIN AUTHOR A
    ON B.AUTHOR_ID = A.AUTHOR_ID) T2
ON T1.BOOK_ID = T2.BOOK_ID
WHERE DATE_FORMAT(T1.SALES_DATE, "%Y-%m") = '2022-01'
GROUP BY T2.AUTHOR_NAME, T2.CATEGORY
ORDER BY T2.AUTHOR_ID, T2.CATEGORY DESC
