# 저자 별, 카테고리 별 매출액


SELECT t1.AUTHOR_ID
    , t3.AUTHOR_NAME
    , t1.CATEGORY
    , SUM(t1.PRICE * t2.SALES) AS TOTAL_SALES
FROM BOOK t1
JOIN (
    SELECT BOOK_ID
        , SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01%'
    GROUP BY BOOK_ID) t2
ON t1.BOOK_ID = t2.BOOK_ID
JOIN AUTHOR t3
ON t1.AUTHOR_ID = t3.AUTHOR_ID
GROUP BY t1.AUTHOR_ID
    , t1.CATEGORY
ORDER BY t1.AUTHOR_ID
    , t1.CATEGORY DESC

