-- 코드를 입력하세요
SELECT C.AUTHOR_ID, C.AUTHOR_NAME, C.CATEGORY, SUM(B.SALES * C.PRICE) AS TOTAL_SALES
FROM BOOK_SALES B
JOIN (SELECT A.AUTHOR_NAME, A.AUTHOR_ID, B.BOOK_ID, B.CATEGORY, B.PRICE
      FROM AUTHOR A
      JOIN BOOK B
      ON A.AUTHOR_ID = B.AUTHOR_ID     
     ) C
ON B.BOOK_ID = C.BOOK_ID
WHERE DATE_FORMAT(B.SALES_DATE, "%Y-%m") = '2022-01'
GROUP BY C.AUTHOR_NAME, C.CATEGORY
ORDER BY C.AUTHOR_ID, C.CATEGORY DESC

# SELECT A.AUTHOR_NAME, A.AUTHOR_ID, B.BOOK_ID, B.CATEGORY, B.PRICE
#       FROM AUTHOR A
#       JOIN BOOK B
#       ON A.AUTHOR_ID = B.AUTHOR_ID  
      
# SELECT * FROM BOOK_SALES
# WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-01"