# CAR_RENTAL_COMPANY_CAR : 대여 중인 자동차 정보
# CAR_RENTAL_COMPANY_RENTAL_HISTORY : 자동차 대여 기록 정보
# CAR_RENTAL_COMPANY_DISCOUNT_PLAN : 종류, 기간 별 할인 정책 정보

SELECT t1.CAR_ID
    , t1.CAR_TYPE
    , ROUND((t1.DAILY_FEE * 30) * (1 - (t2.DISCOUNT_RATE / 100))) AS FEE
FROM (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM (
        SELECT CAR_ID, CAR_TYPE, DAILY_FEE
        FROM CAR_RENTAL_COMPANY_CAR
        WHERE CAR_TYPE = '세단' OR CAR_TYPE = 'SUV') AS t1
    WHERE CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS t2
        WHERE t1.CAR_ID = t2.CAR_ID
            AND (END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'))) AS t1
JOIN (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상') AS t2
ON t1.CAR_TYPE = t2.CAR_TYPE
GROUP BY t1.CAR_ID
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC
    , t1.CAR_TYPE
    , t1.CAR_ID DESC