SELECT
    T1.FOOD_TYPE,
    T1.REST_ID,
    T1.REST_NAME,
    T1.FAVORITES
FROM REST_INFO T1
JOIN
    (SELECT
        FOOD_TYPE,
        MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE) T2
ON T1.FOOD_TYPE = T2.FOOD_TYPE
    AND T1.FAVORITES = T2.MAX_FAVORITES
ORDER BY T1.FOOD_TYPE DESC