SELECT
    E1.ID,
    CASE WHEN
        E2.SIZE <= 0.25 THEN "CRITICAL"
        WHEN E2.SIZE <= 0.5 THEN "HIGH"
        WHEN E2.SIZE <= 0.75 THEN "MEDIUM"
        ELSE "LOW"
        END AS COLONY_NAME
FROM ECOLI_DATA E1
JOIN
(SELECT
    ID,
    PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE
FROM ECOLI_DATA) E2
ON E1.ID = E2.ID
ORDER BY E1.ID