SELECT YEAR(t1.SALES_DATE) AS YEAR
    , MONTH(t1.SALES_DATE) AS MONTH
    , t2.GENDER
    , COUNT(DISTINCT t1.USER_ID) AS USERS
FROM ONLINE_SALE t1
JOIN USER_INFO t2
ON t1.USER_ID = t2.USER_ID
WHERE t2.GENDER IS NOT NULL
GROUP BY YEAR(t1.SALES_DATE)
    , MONTH(t1.SALES_DATE)
    , t2.GENDER
ORDER BY YEAR
    , MONTH
    , GENDER