-- 코드를 입력하세요
# 입양을 간 기록은 있는데, 보호소에 들어온 기록이 없는 동물
# OUTS에는 있지만, INS에는 없음
# SELECT O.ANIMAL_ID, O.NAME
# FROM ANIMAL_INS O
# LEFT JOIN ANIMAL_OUTS I
# ON I.ANIMAL_ID = O.ANIMAL_ID
# WHERE I.ANIMAL_ID IS NULL
# ORDER BY O.ANIMAL_ID

SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_OUTS A
LEFT JOIN (SELECT O.ANIMAL_ID, O.ANIMAL_TYPE AS OUT_TYPE , I.ANIMAL_TYPE AS IN_TYPE
           FROM ANIMAL_OUTS O
           LEFT JOIN ANIMAL_INS I
           ON O.ANIMAL_ID = I.ANIMAL_ID
          ) B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.IN_TYPE IS NULL
ORDER BY A.ANIMAL_ID, A.NAME;
