-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_OUTS A
LEFT JOIN (SELECT O.ANIMAL_ID, O.ANIMAL_TYPE AS OUT_TYPE , I.ANIMAL_TYPE AS IN_TYPE
           FROM ANIMAL_OUTS O
           LEFT JOIN ANIMAL_INS I
           ON O.ANIMAL_ID = I.ANIMAL_ID
          ) B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.IN_TYPE IS NULL
ORDER BY A.ANIMAL_ID, A.NAME;


# SELECT O.ANIMAL_ID, I.ANIMAL_ID
#            FROM ANIMAL_OUTS O
#            LEFT JOIN ANIMAL_INS I
#            ON O.ANIMAL_ID = I.ANIMAL_ID