SELECT YEAR(T2.SALES_DATE) AS YEAR
    , MONTH(T2.SALES_DATE) AS MINTH
    , COUNT(DISTINCT T2.USER_ID) AS PURCHASE_USERS
    , ROUND(COUNT(DISTINCT T2.USER_ID) / (SELECT COUNT(DISTINCT(USER_ID)) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PURCHASE_RATIO
FROM USER_INFO T1
JOIN ONLINE_SALE T2
ON T1.USER_ID = T2.USER_ID
WHERE T1.JOINED LIKE '2021%'
GROUP BY YEAR(T2.SALES_DATE), MONTH(T2.SALES_DATE)
ORDER BY YEAR(T2.SALES_DATE), MONTH(T2.SALES_DATE)











