SELECT t1.PRODUCT_ID AS PRODUCT_ID
    , t1.PRODUCT_NAME AS PRODUCT_NAME
    , (t1.PRICE * t2.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS t1
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
    GROUP BY PRODUCT_ID) AS t2
ON t1.PRODUCT_ID = t2.PRODUCT_ID
ORDER BY TOTAL_SALES DESC
    , t1.PRODUCT_ID