# 코드를 입력하세요
# SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.PRICE * B.AMOUNT) AS TOTAL_SALES
# FROM FOOD_PRODUCT A
# JOIN FOOD_ORDER B
# ON A.PRODUCT_ID = B.PRODUCT_ID
# WHERE DATE_FORMAT(B.PRODUCE_DATE, '%Y-%m') = '2022-05'
# GROUP BY A.PRODUCT_NAME
# ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID

SELECT T1.PRODUCT_ID
    , T1.PRODUCT_NAME
    , SUM(T1.PRICE * T2.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS T1
JOIN (SELECT PRODUCT_ID, AMOUNT
      FROM FOOD_ORDER
      WHERE PRODUCE_DATE LIKE '2022-05%') AS T2
ON T1.PRODUCT_ID = T2.PRODUCT_ID
GROUP BY T1.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, T1.PRODUCT_ID 











