SELECT
    DISTINCT(ID),
    EMAIL,
    FIRST_NAME,
    LAST_NAME
FROM DEVELOPERS T1
JOIN
    (SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End') T2
ON T1.SKILL_CODE & T2.CODE > 0
ORDER BY ID