SELECT
    USER_ID,
    NICKNAME,
    TOTAL_SALES
FROM USED_GOODS_USER T1
JOIN
    (SELECT 
        WRITER_ID,
        SUM(PRICE) TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000) T2
ON T1.USER_ID = T2.WRITER_ID
ORDER BY TOTAL_SALES