SELECT
    T1.MEMBER_NAME,
    REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE T1
JOIN REST_REVIEW T2
ON T1.MEMBER_ID = T2.MEMBER_ID
WHERE T1.MEMBER_ID IN
    (SELECT
        MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(REVIEW_TEXT) = 
            (SELECT COUNT(REVIEW_TEXT)
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY COUNT(REVIEW_TEXT) DESC
            LIMIT 1))
ORDER BY REVIEW_DATE, REVIEW_TEXT