SELECT ITEM_ID, ITEM_NAME, RARITY FROM ITEM_INFO I
JOIN (SELECT T.ITEM_ID AS ID FROM ITEM_TREE T
        JOIN ITEM_INFO I
        ON I.ITEM_ID = T.PARENT_ITEM_ID
        WHERE I.RARITY = "RARE") S
ON I.ITEM_ID = S.ID
ORDER BY ITEM_ID DESC