SELECT MONTH(START_DATE) AS `MONTH`
    , t1.CAR_ID
    , COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS t1
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5) AS t2
ON t1.CAR_ID = t2.CAR_ID
WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY t1.CAR_ID
    , `MONTH`
ORDER BY `MONTH`
    , t1.CAR_ID DESC