SELECT t1.ID
    , t2.FISH_NAME
    , t1.LENGTH
FROM FISH_INFO t1
JOIN FISH_NAME_INFO t2
ON t1.FISH_TYPE = t2.FISH_TYPE
WHERE LENGTH IS NOT NULL
    AND (t1.FISH_TYPE, LENGTH) IN (
        SELECT FISH_TYPE, MAX(LENGTH)
        FROM FISH_INFO
        GROUP BY FISH_TYPE)
ORDER BY t1.ID