SELECT
    FI.ID,
    FN.FISH_NAME,
    FI.MAX_LENGTH AS LENGTH
FROM
    (SELECT
        F1.ID,
        F1.FISH_TYPE,
        F2.MAX_LENGTH
    FROM FISH_INFO F1
    JOIN
        (SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
        FROM FISH_INFO
        GROUP BY FISH_TYPE) F2
    ON F1.FISH_TYPE = F2.FISH_TYPE AND F1.LENGTH = MAX_LENGTH) FI
JOIN FISH_NAME_INFO FN
ON FI.FISH_TYPE = FN.FISH_TYPE
