-- 코드를 작성해주세요
SELECT SCORE
    , T1.EMP_NO
    , T1.EMP_NAME
    , T1.POSITION
    , T1.EMAIL
FROM HR_EMPLOYEES T1
JOIN (SELECT EMP_NO, SUM(SCORE) AS SCORE
      FROM HR_GRADE
      GROUP BY EMP_NO
      ORDER BY SCORE DESC
      LIMIT 1) T2
ON T1.EMP_NO = T2.EMP_NO