# 부서별 평균 연봉
# 소수점 첫째 자리에서 반올림

SELECT t1.DEPT_ID
    , t1.DEPT_NAME_EN
    , ROUND(t2.AVG_SAL) AS AVG_SAL
FROM HR_DEPARTMENT t1
JOIN (
    SELECT DEPT_ID, AVG(SAL) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID) t2
ON t1.DEPT_ID = t2.DEPT_ID
ORDER BY AVG_SAL DESC