SELECT
    CATEGORY,
    SUM(T2.SALES) AS TOTAL_SALES
FROM BOOK T1
JOIN 
    (SELECT BOOK_ID, SALES
    FROM BOOK_SALES
    WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01') T2
ON T1.BOOK_ID = T2.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY