SELECT
    CATEGORY,
    MAX(PRICE) AS MAX_PRICE,
    PRODUCT_NAME
FROM FOOD_PRODUCT T1
WHERE 
    PRICE = (SELECT MAX(PRICE)
                FROM FOOD_PRODUCT
                GROUP BY CATEGORY
                HAVING CATEGORY = T1.CATEGORY)
    AND
    CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC