SELECT COUNT(*) AS FISH_COUNT
    , MAX(LENGTH) AS MAX_LENGTH
    , t1.FISH_TYPE
FROM FISH_INFO t1
JOIN (
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG(
        CASE 
            WHEN LENGTH IS NULL THEN 10
            ELSE LENGTH
        END
    ) >= 33) t2
ON t1.FISH_TYPE = t2.FISH_TYPE
GROUP BY t1.FISH_TYPE
ORDER BY t1.FISH_TYPE