-- 코드를 입력하세요
# SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, "%Y-%m-%d") AS PUBLISHED_DATE
# FROM BOOK B
# JOIN AUTHOR A
# ON B.AUTHOR_ID = A.AUTHOR_ID
# WHERE B.CATEGORY = '경제'
# ORDER BY PUBLISHED_DATE

# '경제' 카테고리 도서 ID, 저자명, 출판일 출력
SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, "%Y-%m-%d") AS PUBLISHED_DATE
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE B.CATEGORY = '경제'
ORDER BY B.PUBLISHED_DATE